#!/bin/sh
export FORTIFY_HOME=/tools/fortify
export FORTIFY_SCANCENTRAL_HOME=$FORTIFY_HOME
export CATALINA_HOME=$FORTIFY_SCANCENTRAL_HOME/tomcat
export PATH=$CATALINA_HOME/bin:$FORTIFY_SCANCENTRAL_HOME/bin:$PATH
